name: example
description: A test project to prove Nevaeh UI works.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  nevaeh_ui:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0

